### ISSUE TITLE
execv error: No such file or directory

### ISSUE THREAD

**Issue by akram1** [zyrouge/android-studio-preview-appimage#1]
I have Linux Manjaro (latest) using wayland. I have couple of AppImage apps running execept android-sutido (latest). It does not run and in terminal give me 
execv error: No such file or directory

**Comment by zyrouge** [comment]
Could you send a screenshot of that?

**Comment by akram1** [comment]
Update: with x11 session I got this error
Qt: Session management error: None of the authentication protocols specified are supported
execv error: No such file or directory

**Comment by akram1** [comment]
![Screenshot_20240725_192123](https://github.com/user-attachments/assets/b0489db1-66fa-4216-b76c-a84aa58545e2)

**Comment by akram1** [comment]
Update: I tried sudo it workd and a pop up window (running for the first time) then displaced the appimage file into root directory, and here is what I got:
sudo ./android-studio-2024.1.1.11-x86_64_a17149463b739027d4ba415166f93724.appimage                                                                 127 ✘ 
[sudo] password for akram: 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Failed to connect to bus: No medium found
Failed to connect to bus: No medium found
[AppImageLauncher] Warning: can't find fallback icon for namedialog-ok
[AppImageLauncher] Warning: can't find fallback icon for namedialog-cancel
[AppImageLauncher] Warning: can't find fallback icon for namedocument-revert
Extracting usr/share/icons/hicolor/1024x1024/apps/android-studio.png to "/root/.local/share/icons/hicolor/1024x1024/apps/appimagekit_899063e6171595c6fdf74659473fd468_android-studio.png"
Extracting usr/share/icons/hicolor/256x256/apps/android-studio.png to "/root/.local/share/icons/hicolor/256x256/apps/appimagekit_899063e6171595c6fdf74659473fd468_android-studio.png"
Extracting usr/share/icons/hicolor/512x512/apps/android-studio.png to "/root/.local/share/icons/hicolor/512x512/apps/appimagekit_899063e6171595c6fdf74659473fd468_android-studio.png"
WARNING: Unable to resize the application icon into a 128x128 image: "Unable to load image.". It will be written unchanged.
WARNING: Unable to resize the application icon into a 256x256 image: "Unable to load image.". It will be written unchanged.
gtk-update-icon-cache: Cache file created successfully.
which: no gtk-update-icon-cache-3.0 in (/home/akram/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin)
which: no update-icon-caches in (/home/akram/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin)
Directory '/root/.local/share/mime/packages' does not exist!
execv error: No such file or directory


I put the imagefile back to where it was and change the ownership to me. I still got the same problem before.

**Comment by zyrouge** [comment]
Refer [this](https://github.com/AppImage/AppImageKit/issues/508). There are plenty of similar issues, kindly refer those.

**Comment by Samueru-sama** [comment]
This is caused by appimagelauncher, if you remove it (and reboot) it goes away.

**Comment by akram1** [comment]
Thnak you Samueru-sama. Removing appimagelauncher fixed the problem.

**Comment by Samueru-sama** [comment]
> Thnak you Samueru-sama. Removing appimagelauncher fixed the problem.

Btw If you want an alternative for appimagelauncher, [check this](https://github.com/ivan-hc/AM)
